[COS-624] enable FE tests

diff --git a/.github/workflows/build-spaces.yml b/.github/workflows/build-spaces.yml
--- a/.github/workflows/build-spaces.yml
+++ b/.github/workflows/build-spaces.yml
@@ -42,15 +42,17 @@ jobs:
 
       - name: Deploy test Environment
         run: |
-          set -e
           curl http://openline.sh/install.sh | sh
-          openline dev start
-          echo "[INFO] Checking Openline CLI services..."
-          openline dev ping || { echo 'Openline CLI services check failed' ; exit 1; }
-          echo "[INFO] Checking PODs..."
-          kubectl -n openline get pods || { echo 'PODs check failed' ; exit 1; }
-          echo "[INFO] wait for 3 seconds to make sure all services are up and running..."
-          sleep 3
+#      - name: Deploy test Environment
+#        run: |
+#          curl http://openline.sh/install.sh | sh
+#          openline dev start
+#          echo "[INFO] Checking Openline CLI services..."
+#          openline dev ping || { echo 'Openline CLI services check failed' ; exit 1; }
+#          echo "[INFO] Checking PODs..."
+#          kubectl -n openline get pods || { echo 'PODs check failed' ; exit 1; }
+#          echo "[INFO] wait for 3 seconds to make sure all services are up and running..."
+#          sleep 3
 
       - name: Test GraphQL contracts
         run: |
