Align workflows and squash them (#2914)

diff --git a/.github/workflows/build-anthropic-api.yml b/.github/workflows/build-anthropic-api.yml
--- a/.github/workflows/build-anthropic-api.yml
+++ b/.github/workflows/build-anthropic-api.yml
@@ -1,19 +1,23 @@
-name: Publish events-processing-platform
+name: anthropic-api
 
 on:
   push:
     branches: [ "otter" ]
     paths:
       - packages/server/customer-os-common-module/**
-      - packages/server/events-processing-common/**
-      - packages/server/events-processing-platform/**
-      - .github/workflows/publish-events-processing-platform.yml
+      - packages/server/anthropic-api/**
+      - .github/workflows/build-anthropic-api.yml
+  pull_request:
+    paths:
+      - packages/server/customer-os-common-module/**
+      - packages/server/anthropic-api/**
+      - .github/workflows/build-anthropic-api.yml
   release:
     types: [ created, edited ]
 
 env:
   REGISTRY: ghcr.io
-  IMAGE_NAME: ${{ github.repository }}/events-processing-platform
+  IMAGE_NAME: ${{ github.repository }}/anthropic-api
 
 permissions:
   contents: read
@@ -22,10 +26,11 @@ permissions:
 
 defaults:
   run:
-    working-directory: ./packages/server/events-processing-platform
+    working-directory: ./packages/server/anthropic-api
 
 jobs:
-  build:
+  test:
+    
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -33,54 +38,41 @@ jobs:
       - name: Set up Go
         uses: actions/setup-go@v4
         with:
-          go-version: '1.20.5'
+          go-version: stable
 
       - name: Build
+        working-directory: ./packages/server/anthropic-api
         run: make all
 
       - name: Test
-        run: gotestsum --junitfile unit-tests.xml -- -coverprofile=cover.out ./...
-
+        working-directory: ./packages/server/anthropic-api
+        run: |
+          go install gotest.tools/gotestsum@latest
+          gotestsum --junitfile unit-tests.xml -- -coverprofile=cover.out ./...
       - name: Test Report
         uses: mikepenz/action-junit-report@v3
-        if: always()    # run this step even if previous step failed
+        if: success() || failure()    # run this step even if previous step failed
         with:
-          report_paths: ./packages/server/events-processing-platform/unit-tests.xml    # Path to test results
+          report_paths: packages/server/anthropic-api/unit-tests.xml    # Path to test results
           include_passed: true
           annotate_only: true
           detailed_summary: true
 
       - name: Compute Code Coverage
+        working-directory: ./packages/server/anthropic-api
         run: |
           echo "## Code Coverage" >> $GITHUB_STEP_SUMMARY
           echo "|Filename|Function|Coverage|" >> $GITHUB_STEP_SUMMARY
           echo "|--------|--------|--------|" >> $GITHUB_STEP_SUMMARY
           go tool cover -func=cover.out |sed -r  's/[[:space:]]+/|/g'|sed -r 's/$/|/g'|sed -r 's/^/|/g' >> $GITHUB_STEP_SUMMARY
 
-  publish:
-    name: publish image
+  build-publish:
     needs:
-      - build
+      - test
 
     runs-on: ubuntu-latest
-
     steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-
-      - name: Prepare sources for docker build
-        run: |
-          mkdir tmp-sources
-          mkdir tmp-sources/customer-os-common-module
-          mkdir tmp-sources/events-processing-platform
-          mkdir tmp-sources/events-processing-common
-          
-          rsync -av --progress --exclude="tmp-sources" * tmp-sources/events-processing-platform
-          cp .env tmp-sources/events-processing-platform/.env
-          cp -r ../customer-os-common-module/* tmp-sources/customer-os-common-module
-          cp -r ../events-processing-common/* tmp-sources/events-processing-common
-          
-          cp Dockerfile tmp-sources/Dockerfile
+      - uses: actions/checkout@v3
 
       - name: Log in to the Container registry
         uses: docker/login-action@v2.2.0
@@ -98,7 +90,8 @@ jobs:
       - name: Push Docker image
         uses: docker/build-push-action@v4.1.1
         with:
-          context: packages/server/events-processing-platform/tmp-sources/.
-          push: true
+          context: ./packages/server/
+          file: ./packages/server/anthropic-api/Dockerfile
+          push: ${{ github.ref_name == 'otter' || github.event_name == 'release' }}
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
