Initial commit for performance testing

diff --git a/.github/workflows/performance-tests.yml b/.github/workflows/performance-tests.yml
--- a/.github/workflows/performance-tests.yml
+++ b/.github/workflows/performance-tests.yml
@@ -37,7 +37,7 @@ jobs:
       - name: Check average response time
         run: |
           averageResponseTime=$(awk -F',' '{sum+=$2; count++} END {print sum/count}' test_results.jtl)
-          responseTimeThreshold=100
+          responseTimeThreshold=400
           echo "responseTimeThreshold=$responseTimeThreshold" >> $GITHUB_ENV
           echo "averageResponseTime=$averageResponseTime" >> $GITHUB_ENV
 
@@ -47,10 +47,14 @@ jobs:
           fi
         id: check_response_time
 
-      - name: Set pipeline status
+      - name: Tests failure
+        if: steps.check_response_time.outputs.threshold_exceeded == 'true'
         run: |
-          if [[ steps.check_response_time.outputs.threshold_exceeded == 'true' ]]; then
-            echo "::error title=Average response time ($averageResponseTime ms) exceeds the threshold of $responseTimeThreshold ms."
-            exit 1
-          else 
-            echo "::notice title=Average response time ($averageResponseTime ms) does not exceed the threshold of $responseTimeThreshold ms."
+          echo "::error title=Average response time ($averageResponseTime ms) exceeds the threshold of $responseTimeThreshold ms."
+          exit 1
+
+      - name: Tests passed
+        if: steps.check_response_time.outputs.threshold_exceeded != 'true'
+        run: |
+          echo "::notice title=Average response time ($averageResponseTime ms) doesn't exceed the threshold of $responseTimeThreshold ms."
+          exit 1
